name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Creer fichier .env
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo02_db" >> .env
          echo "DB_USER=labo02" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
          echo "REDIS_HOST=127.0.0.1" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
        
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..20}; do
            if mysqladmin ping --protocol=tcp -h 127.0.0.1 -uroot -proot --silent; then
              echo "MySQL is ready"
              exit 0
            fi
            echo "Waiting for MySQL (attempt $i)..."
            sleep 5
          done
          echo "MySQL did not become ready in time" >&2
          exit 1

      - name: Initialize database schema
        run: |
          mysql --protocol=tcp -h 127.0.0.1 -uroot -proot mydb < db-init/init.sql

      - name: Run tests
        run: |
          cd src
          python3 -m pytest -v